version: 0.2

env:
  variables:
    REPOSITORY_URI: "637318189758.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo"
    AWS_REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=$COMMIT_HASH
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json with IMAGE_URI=$IMAGE_URI
      - printf '[{"name":"my-app","imageUri":"%s"}]' "$IMAGE_URI" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
